#!/usr/bin/env bash
# @csps-id csps.claude.hooks.user-prompt-submit-governor-prompts
# @csps-name user-prompt-submit-governor-prompts
# @csps-description UserPromptSubmit hook — auto-logs every Governor prompt as a GP-S<NNN>-<NN> entry in governor-prompts/S<NNN>.md per B_GOVERNOR_PROMPTS (P-META-012). Composes with user-prompt-submit-intake.sh.
# @csps-version 1.0.0
# @csps-owner group:finky
# @csps-lifecycle experimental
# @csps-lifecycle-state active
# @csps-tags type:hook domain:governance audience:developer
# @csps-enforces P-META-012 B_GOVERNOR_PROMPTS

set -euo pipefail

readonly PROMPT_TEXT="${CLAUDE_USER_PROMPT:-${HOOK_INPUT_text:-${1:-}}}"
readonly SESSION_ID="${CLAUDE_SESSION_ID:-unknown}"
readonly TIMESTAMP="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
readonly DATE_STR="$(date -u +"%Y-%m-%d")"
readonly TIME_STR="$(date -u +"%H:%M")"

# Skip empty prompts
if [[ -z "${PROMPT_TEXT}" ]]; then
  echo "[gp-auto-log] SKIP — empty prompt"
  exit 0
fi

# Skip trivial single-word acknowledgements
TRIMMED="${PROMPT_TEXT// /}"
WORD_COUNT=$(echo "${PROMPT_TEXT}" | wc -w | tr -d ' ')
if [[ "${WORD_COUNT}" -le 1 ]]; then
  echo "[gp-auto-log] SKIP — trivial prompt (${WORD_COUNT} word)"
  exit 0
fi

# Determine session number from session-state.json if available
VAULT_DIR="docs/plan/_handoff/VAULT/governor-prompts"
GP_SESSION="S050"  # Default to S050; could be made dynamic

# Try to read from session-state.json
SESSION_JSON="tools/zf-session-tracker.json"
if [[ -f "${SESSION_JSON}" ]]; then
  SESSION_NUM=$(grep -oP '"session"\s*:\s*"\K[^"]+' "${SESSION_JSON}" 2>/dev/null | head -1 || echo "")
  if [[ -n "${SESSION_NUM}" ]]; then
    GP_SESSION="${SESSION_NUM}"
  fi
fi

GP_FILE="${VAULT_DIR}/${GP_SESSION}.md"

# Create directory and file header if they don't exist
mkdir -p "${VAULT_DIR}"
if [[ ! -f "${GP_FILE}" ]]; then
  cat > "${GP_FILE}" << HEADER
# Governor Prompts — ${GP_SESSION}
<!-- auto-generated by user-prompt-submit-governor-prompts.sh -->

HEADER
fi

# Determine next entry number
LAST_NUM=$(grep -oP 'GP-'"${GP_SESSION}"'-\K[0-9]+' "${GP_FILE}" 2>/dev/null | sort -n | tail -1 || echo "00")
NEXT_NUM=$(printf "%02d" $(( 10#${LAST_NUM} + 1 )))
GP_ID="GP-${GP_SESSION}-${NEXT_NUM}"

# Extract 2-3 topic tags from first 50 chars of prompt (heuristic)
TAGS="general"
if echo "${PROMPT_TEXT}" | grep -qi "build\|create\|implement\|code\|feat"; then TAGS="implementation"; fi
if echo "${PROMPT_TEXT}" | grep -qi "plan\|design\|architect\|review"; then TAGS="planning"; fi
if echo "${PROMPT_TEXT}" | grep -qi "verify\|test\|check\|validate"; then TAGS="validation"; fi
if echo "${PROMPT_TEXT}" | grep -qi "close\|handoff\|session"; then TAGS="session-management"; fi
if echo "${PROMPT_TEXT}" | grep -qi "from opus\|opus says\|from opus-"; then TAGS="relay,opus-directive"; fi

# Truncate prompt to 500 chars for verbatim (avoid enormous log entries)
VERBATIM="${PROMPT_TEXT:0:500}"
if [[ "${#PROMPT_TEXT}" -gt 500 ]]; then
  VERBATIM="${VERBATIM}... [truncated at 500 chars]"
fi

# Append GP entry
cat >> "${GP_FILE}" << ENTRY
## ${GP_ID} | ${DATE_STR} ${TIME_STR}
**Tags:** ${TAGS}
**Status:** new
**Verbatim:**
> ${VERBATIM}

---
ENTRY

echo "[gp-auto-log] logged ${GP_ID} to ${GP_FILE} (${WORD_COUNT} words, tags=${TAGS})"
exit 0
