#!/usr/bin/env bash
# @csps-id csps.claude.hooks.user-prompt-submit-raw-comments
# @csps-name user-prompt-submit-raw-comments
# @csps-description UserPromptSubmit hook — saves every Governor comment raw and unchanged
#   with session ID + date + time. Per Governor directive S021: "I have a future idea on how
#   to use them." Append-only log. Never modifies, never filters, never summarizes.
#   The raw comment IS the artifact.
# @csps-version 1.0.0
# @csps-owner group:finky
# @csps-lifecycle production
# @csps-lifecycle-state active
# @csps-tags type:hook domain:governance audience:developer
# @csps-enforces B_GOVERNOR_PROMPTS

set -euo pipefail

STDIN_JSON="$(cat 2>/dev/null || true)"
RAW_COMMENT="$(STDIN_JSON="$STDIN_JSON" node -e 'try{const j=JSON.parse(process.env.STDIN_JSON||"{}");process.stdout.write(j.prompt||"")}catch(e){}' 2>/dev/null || true)"
RAW_COMMENT="${RAW_COMMENT:-${CLAUDE_USER_PROMPT:-${1:-}}}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SESSION_ID="$(node "${REPO_ROOT}/tools/lib/session-source.mjs" 2>/dev/null || echo "${CLAUDE_SESSION_ID:-S086}")"
TIMESTAMP="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
DATE_PART="$(date -u +"%Y-%m-%d")"

# Output directory — one file per day, append-only
COMMENTS_DIR="${REPO_ROOT}/docs/plan/_handoff/VAULT/governor-comments"
mkdir -p "$COMMENTS_DIR" 2>/dev/null || true
OUTPUT_FILE="${COMMENTS_DIR}/${DATE_PART}.md"

# Skip empty prompts
[ -z "$RAW_COMMENT" ] && exit 0

# A1 S086: write YAML frontmatter at file create so validators pass
if [ ! -f "$OUTPUT_FILE" ]; then
  {
    echo "---"
    echo "id: csps.handoff.vault.governor-comments.${DATE_PART}"
    echo "name: governor-comments-${DATE_PART}"
    echo "description: 'Auto-generated governor comment log for ${DATE_PART}'"
    echo "type: log"
    echo "lifecycle_state: active"
    echo "owner: group:finky"
    echo "session: ${SESSION_ID}"
    echo "date: '${DATE_PART}'"
    echo "---"
    echo ""
    echo "# Governor Comments — ${DATE_PART}"
    echo "<!-- auto-generated by user-prompt-submit-raw-comments.sh -->"
    echo ""
  } > "$OUTPUT_FILE" 2>/dev/null || true
fi

# Append raw comment with metadata header
{
  echo ""
  echo "---"
  echo "## [${TIMESTAMP}] session=${SESSION_ID}"
  echo ""
  echo "${RAW_COMMENT}"
  echo ""
} >> "$OUTPUT_FILE" 2>/dev/null || true

# Silent — no output to avoid cluttering session start
exit 0
