/**
 * @csps-id csps.principles.split
 * @csps-name principles-split
 * @csps-description Phase 7 generator (token-optimization §9.8 Candidate #1). Reads principles.yaml
 * and emits one YAML slice file per principle at packages/principles/principles/P-XXX-NNN.yaml plus
 * a lightweight principles-index.yaml manifest. Codegen (codegen.ts) continues to read the monolith
 * for batch artifact generation; AI sessions load individual slices for context efficiency
 * (85K monolith → 3-8K per-principle slice). Per P-META-009 B_TOKEN_BUDGET R1 + depth-discipline.md.
 *
 * Run: pnpm --filter @csps/principles split
 * Or:  pnpm principles:split (root alias, once registered)
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const REGISTRY_PATH = join(__dirname, 'principles.yaml');
const SLICES_DIR    = join(__dirname, 'principles');
const INDEX_PATH    = join(__dirname, 'principles-index.yaml');

// ── Load source ───────────────────────────────────────────────────────────────

const raw = readFileSync(REGISTRY_PATH, 'utf8');
const registry = yaml.load(raw);
const principles = registry.principles ?? [];

if (principles.length === 0) {
  console.error('[split-principles] ERROR: no principles found in principles.yaml');
  process.exit(1);
}

// ── Ensure output dir ─────────────────────────────────────────────────────────

if (!existsSync(SLICES_DIR)) mkdirSync(SLICES_DIR, { recursive: true });

// ── Emit slice files ──────────────────────────────────────────────────────────

const indexEntries = [];
let written = 0;

for (const principle of principles) {
  const { id } = principle;
  if (!id) continue;

  const filename = `${id}.yaml`;
  const filePath = join(SLICES_DIR, filename);
  const relPath  = `./principles/${filename}`;

  // Header comment — explains provenance; prevents direct edits
  const header = [
    `# ${id}.yaml`,
    `# CSPS Principle Slice — generated by tools/split.mjs`,
    `# Source of truth: packages/principles/principles.yaml`,
    `# DO NOT edit this file directly — run \`pnpm --filter @csps/principles split\` to regenerate`,
    `# Phase 7 token-optimization §9.8 Candidate #1 (S010)`,
    `# Load this file (${filename}) instead of the full principles.yaml (~85K)`,
    `# when you only need this one principle in your AI session context.`,
    ``,
  ].join('\n');

  const content = header + yaml.dump(principle, {
    indent: 2,
    lineWidth: 120,
    noRefs: true,
  });

  writeFileSync(filePath, content, 'utf8');
  written++;

  indexEntries.push({
    id,
    name:     principle.name ?? '',
    category: principle.category ?? '',
    severity: principle.severity ?? '',
    path:     relPath,
  });
}

// ── Emit index file ───────────────────────────────────────────────────────────

const indexHeader = [
  `# principles-index.yaml`,
  `# CSPS Principles Index — generated by tools/split.mjs`,
  `# Lightweight manifest: use this to discover which slice file to load`,
  `# instead of loading the full 85K principles.yaml.`,
  `# Source: packages/principles/principles.yaml`,
  `# Run \`pnpm --filter @csps/principles split\` to regenerate after editing principles.yaml`,
  ``,
].join('\n');

const indexDoc = {
  meta: {
    total_count: indexEntries.length,
    generated_at: new Date().toISOString().slice(0, 10),
    source: 'packages/principles/principles.yaml',
    slices_dir: 'packages/principles/principles/',
    usage: 'Load individual slice files (./principles/P-XXX-NNN.yaml) for AI session context; load this index to discover available principles without loading full monolith',
  },
  principles: indexEntries,
};

writeFileSync(INDEX_PATH, indexHeader + yaml.dump(indexDoc, { indent: 2, lineWidth: 120 }), 'utf8');

console.log(`[split-principles] ✓ wrote ${written} slice files → ${SLICES_DIR}`);
console.log(`[split-principles] ✓ wrote index → ${INDEX_PATH}`);
console.log(`[split-principles] total_count=${indexEntries.length}`);
