/**
 * @csps-id csps.libs.threshold.intake
 * Threshold session intake — wires classify() + route() to the CSPS intake pipeline.
 * Processes governor inputs: classifies type, determines pipeline, writes to intake log.
 * Design: docs/SIA/R1-04-THRESHOLD.md § 7 (Developer Journey)
 * Design: docs/SIA/INFRA-FLOW-VALIDATION.md Step 1 (IDEA → THRESHOLD)
 * Plan item: INFRA-FLOW-VALIDATION | S056 | Layer 3
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { classify } from './classifier.js';
import { route } from './router.js';
import type { ThresholdInput, RoutingResult, ThresholdInputType, InputSource } from './types.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../../..');
const INTAKE_DIR = join(ROOT, '.csps', 'threshold');
const INTAKE_LOG = join(INTAKE_DIR, 'intake-log.yaml');

export interface ThresholdIntakeRecord {
  id: string;
  raw: string;
  session: string;
  timestamp: string;
  input: ThresholdInput;
  routing: RoutingResult;
}

function ensureDir(): void {
  if (!existsSync(INTAKE_DIR)) mkdirSync(INTAKE_DIR, { recursive: true });
}

function serializeRecord(record: ThresholdIntakeRecord): string {
  return `\n- id: ${record.id}\n  raw: ${JSON.stringify(record.raw.slice(0, 120))}\n  session: ${record.session}\n  timestamp: ${record.timestamp}\n  type: ${record.input.type}\n  spine_tag: ${record.input.spine_tag}\n  scope_tag: ${record.input.scope_tag}\n  urgency: ${record.input.urgency}\n  pipelines: [${record.routing.pipelines.join(', ')}]\n  escalated: ${record.routing.escalated}\n`;
}

/** Classify a raw governor input and write to intake log. Returns the record. */
export function processGovernorInput(
  rawInput: string,
  session: string,
  opts?: { type?: ThresholdInputType; source?: InputSource },
): ThresholdIntakeRecord {
  const input = classify({
    type: opts?.type ?? inferType(rawInput),
    session,
    source: opts?.source ?? 'governor_directive',
    raw: rawInput.slice(0, 500),
  });

  const routing = route(input);

  const record: ThresholdIntakeRecord = {
    id: input.id,
    raw: rawInput.slice(0, 200),
    session,
    timestamp: input.created_at,
    input,
    routing,
  };

  ensureDir();
  const existing = existsSync(INTAKE_LOG) ? readFileSync(INTAKE_LOG, 'utf-8') : '# Threshold intake log\n# Append-only. Generated by libs/threshold/intake.ts\nentries:\n';
  writeFileSync(INTAKE_LOG, existing.trimEnd() + serializeRecord(record) + '\n', 'utf-8');

  return record;
}

/** Get recent intake records (last N lines of log) */
export function getRecentIntake(n = 10): string {
  if (!existsSync(INTAKE_LOG)) return '';
  const lines = readFileSync(INTAKE_LOG, 'utf-8').split('\n');
  return lines.slice(-Math.min(n * 10, lines.length)).join('\n');
}

/** Heuristic: infer input type from raw text characteristics */
function inferType(raw: string): ThresholdInputType {
  const lower = raw.toLowerCase();
  if (/error|fail|broken|crash|exception|not found/.test(lower)) return 'error';
  if (/fix|fixed|resolved|solution|workaround/.test(lower)) return 'solution';
  if (/correction|wrong|incorrect|should be|must be/.test(lower)) return 'correction';
  if (/insight|pattern|realized|discovered|found that/.test(lower)) return 'architectural_insight';
  if (/k=[23456789]|k>=2|recurring|again|still/.test(lower)) return 'core_seed';
  if (/question|unclear|unknown|how do|what is/.test(lower)) return 'question';
  if (/note:|remember|key quote|important/.test(lower)) return 'quote';
  return 'governor_directive';
}
